#!/bin/bash
echo "Hello and Good Morning"
echo "Welcome to the Session"
echo "Hello and Good Morning"
echo "Welcome to the Session"
echo "Hello and Good Morning"
echo "Welcome to the Session"
echo "Hello and Good Morning"
echo "Hello and Good Morning"
echo "Hello and Good Morning"
echo "Hello and Good Morning"
